### PR TITLE
Add 'no-debugger': 0 to .eslintrc

### PR DESCRIPTION
**Pull request by JESii**
Allow debugger statements; as discussed last year in gitter.

### CODE REVIEW

**Comment by JESii** [comment]
Sorry for the revert in the middle of all this; made a mistake and I should have squashed the commits. I can redo the whole thing if you prefer.

**Comment by bebraw** [comment]
Yeah, maybe rebase against `master`. It's good to go after that. 👍

**Comment by bebraw** [comment]
I pushed the fix to the boilerplate to save your time. Thanks for the idea.

**Comment by JESii** [comment]
Thank you very much... I was just starting to take a look. I'll be sure to squash anything else first!

**Pull request closed without merging**
